baseURL = "https://ovaar.github.io/"
title = "Ovaar - Software engineering blog"
copyright = "2020 Ovaar. This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
theme = "lyla"

enableEmoji=true
enableRobotsTXT = true

[taxonomies]
   tag = "tags"
   category = "categories"

[params.social]
    github = "https://github.com/ovaar"
    linkedin = "https://www.linkedin.com/in/thomas-reynders-6bb57057/"

[params]
    Author = "Ovaar"
    Description = "Software Engineering blog"

[permalinks]
    posts = "/:year/:month/:title/"

[imaging]
    resampleFilter = "box"
    quality = 75
    hint = "photo"
    anchor = "smart"
    bgColor = "#ffffff"

[imaging.exif]
    includeFields = ""
    excludeFields = ""
    disableDate = false
    disableLatLong = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4