baseURL = "https://ovaar.github.io/"
title = "Ovaar - Blog"
theme = "lyla"

googleAnalytics = "UA-173180646-1"
enableRobotsTXT = true
[taxonomies]
   tag = "tags"
   category = "categories"

[Social]
    linkedin = "https://www.linkedin.com/in/thomas-reynders-6bb57057/"
    github = "https://github.com/ovaar"

[params]
    Author = "Ovaar"
    Description = "Software Engineering blog"

[permalinks]
    posts = "/:year/:month/:title/"
