version: '3.4'

services:
  blog:
    image: klakegg/hugo:0.73.0
    volumes:
      - .:/src
    environment:
      NODE_ENV: production

  server:
    image: klakegg/hugo:0.73.0
    command: server --verbose
    volumes:
      - .:/src
    ports:
      - 1313:1313
    environment:
      NODE_ENV: production
