
services:
  blog:
    image: ghcr.io/gohugoio/hugo:v0.151.0
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    volumes:
      - ./:/project

  server:
    image: ghcr.io/gohugoio/hugo:v0.151.0
    #bind is inside the container, so this still will only have localhost:1313 listen on the host
    command: serve --port 1313 --bind 0.0.0.0 --disableFastRender --noTimes
    volumes:
      - ./:/project
      - ~/hugo_cache:/cache
    ports:
      - 1313:1313