
services:
  blog:
    image: klakegg/hugo:0.90.1
    volumes:
      - .:/src
    environment:
      NODE_ENV: production

  server:
    image: klakegg/hugo:0.90.1
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"