name: Deploy Blog

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures submodules are initialized and updated
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Get UID and GID
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      - name: Prepare Hugo cache directory
        run: |
          mkdir -p "${{ runner.temp }}/hugo_cache"
          # Show ownership (should match the runner user so container user UID:GID can write)
          ls -ld "${{ runner.temp }}/hugo_cache"

      - name: Run docker compose
        run: |
          docker compose run --rm \
            -v "${{ runner.temp }}/hugo_cache:/cache" \
            blog \
              --gc \
              --minify \
              --noTimes \
              --baseURL "${{ steps.pages.outputs.base_url }}/"
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: public
          branch: master
          push_options: --force
          create_branch: false

        