name: Deploy Blog

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are initialized and updated
          fetch-depth: 0

      - name: Set execute permissions for deploy script
        run: chmod +x ./scripts/deploy.sh

      - name: Run deploy script
        run: ./scripts/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
