name: Deploy Blog

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive  # Ensures submodules are initialized and updated
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - name: Debug
        run: |
          echo "Runner user ID: $(id -u)"
          echo "Runner group ID: $(id -g)"
          echo "Runner home directory: $HOME"
          ls **/*

      - name: Get UID and GID
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      - name: Prepare Hugo cache directory
        run: |
          mkdir -p "${{ runner.temp }}/hugo_cache"
          # Show ownership (should match the runner user so container user UID:GID can write)
          ls -ld "${{ runner.temp }}/hugo_cache"

      - name: Run docker compose
        run: |
          docker compose run --rm \
            -v "${{ runner.temp }}/hugo_cache:/cache" \
            blog \
              --gc \
              --minify \
              --noTimes \
              --baseURL "${{ steps.pages.outputs.base_url }}/"

          cd public
          git add .
          git commit -m "Deploy site $(date)" || echo "No changes to commit"
          git push origin master
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      
        